staticSites:
  - type: static
    name: traffic-congestion-frontend
    env: static
    plan: free
    branch: main
    buildCommand: cd frontend && npm install && npm run build
    publishPath: frontend/dist
services:
  - type: web
    name: traffic-congestion-backend
    env: python
    runtime: python-3.12
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
